# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TelegramMcp < Formula
  desc "Telegram MCP server for AI assistants"
  homepage "https://github.com/wenjebs/telegram-mcp"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wenjebs/telegram-mcp/releases/download/v0.2.0/telegram-mcp_Darwin_x86_64.tar.gz"
      sha256 "9fdb5d925371c6653a8ae8072d61eb1dadd54bfcce587aa31f23bdb22c9f8f0b"

      define_method(:install) do
        bin.install "telegram-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wenjebs/telegram-mcp/releases/download/v0.2.0/telegram-mcp_Darwin_arm64.tar.gz"
      sha256 "fdb1e7c86009f86e4e9fc5bd999fb9cdd43c6c804faa7c822b7b3f3e6d1cb7eb"

      define_method(:install) do
        bin.install "telegram-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wenjebs/telegram-mcp/releases/download/v0.2.0/telegram-mcp_Linux_x86_64.tar.gz"
      sha256 "1a9098f6a969b93e3f9849de1bf657d78639c692031e9a40bdca2d0e3845661a"
      define_method(:install) do
        bin.install "telegram-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wenjebs/telegram-mcp/releases/download/v0.2.0/telegram-mcp_Linux_arm64.tar.gz"
      sha256 "cb3554a476ec4fb0187d14e11d1dba16fb3d963eb7550f709483307796f59c87"
      define_method(:install) do
        bin.install "telegram-mcp"
      end
    end
  end

  test do
    system "#{bin}/telegram-mcp", "--version"
  end
end
