# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TelegramMcp < Formula
  desc "Telegram MCP server for AI assistants"
  homepage "https://github.com/wenjebs/telegram-mcp"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/wenjebs/telegram-mcp/releases/download/v0.1.0/telegram-mcp_Darwin_x86_64.tar.gz"
      sha256 "aed2b5949ffe3204455ac987e134246d35caf1f8a4c52a45db641d2b0cefb093"

      define_method(:install) do
        bin.install "telegram-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/wenjebs/telegram-mcp/releases/download/v0.1.0/telegram-mcp_Darwin_arm64.tar.gz"
      sha256 "0ee968f808780ab1fd93119bd5ff1d0ca6f7764fd1ac251bb32e1dfb0e151cb0"

      define_method(:install) do
        bin.install "telegram-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/wenjebs/telegram-mcp/releases/download/v0.1.0/telegram-mcp_Linux_x86_64.tar.gz"
      sha256 "c07e003f43a7bbf2f9e136ed986e6d39c7f705cbb399331b58cee9f4d5f9e70c"
      define_method(:install) do
        bin.install "telegram-mcp"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/wenjebs/telegram-mcp/releases/download/v0.1.0/telegram-mcp_Linux_arm64.tar.gz"
      sha256 "38828a71df8ca1f258a628ee66678f99e47d3ffc081ee1a13c09eedd9f7d97cd"
      define_method(:install) do
        bin.install "telegram-mcp"
      end
    end
  end

  test do
    system "#{bin}/telegram-mcp", "--version"
  end
end
